## Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([2, -1, 3, 5])
s

0    2
1   -1
2    3
3    5
dtype: int64

In [3]:
np.exp(s)

0      7.389056
1      0.367879
2     20.085537
3    148.413159
dtype: float64

In [4]:
s + [100, 200, 300, 400]

0    102
1    199
2    303
3    405
dtype: int64

In [5]:
s + 100

0    102
1     99
2    103
3    105
dtype: int64

In [6]:
s2 = pd.Series([68, 69, 72, 82], index = ["Alex", "Bob", "Charles", "Darwin"])
s2

Alex       68
Bob        69
Charles    72
Darwin     82
dtype: int64

In [7]:
s2["Charles"]

np.int64(72)

### Dataframe Objects

In [8]:
people_dict = {
    "weight": pd.Series([68, 83, 112], index=["alice", "bob", "charles"]),
    "birthyear": pd.Series([1984, 1985, 1992], index=["bob", "alice", "charles"], name="year"),
    "children": pd.Series([0, 3], index=["charles", "bob"]),
    "hobby": pd.Series(["Biking", "Dancing"], index=["alice", "bob"]),
}

In [9]:
people  = pd.DataFrame(people_dict)
people

         weight  birthyear  children    hobby
alice        68       1985       NaN   Biking
bob          83       1984       3.0  Dancing
charles     112       1992       0.0      NaN

In [10]:
people.T

            alice      bob charles
weight         68       83     112
birthyear    1985     1984    1992
children      NaN      3.0     0.0
hobby      Biking  Dancing     NaN

In [11]:
city_loc = pd.DataFrame(
    [
        ["CA", "San Francisco", 37.781334, -122.416728],
        ["NY", "New York", 40.705649, -74.008344],
        ["FL", "Miami", 25.791100, -80.320733],
        ["OH", "Cleveland", 41.473508, -81.739791],
        ["UT", "Salt Lake City", 40.755851, -111.896657]
    ], columns=["state", "city", "lat", "lng"])
city_loc

  state            city        lat         lng
0    CA   San Francisco  37.781334 -122.416728
1    NY        New York  40.705649  -74.008344
2    FL           Miami  25.791100  -80.320733
3    OH       Cleveland  41.473508  -81.739791
4    UT  Salt Lake City  40.755851 -111.896657

In [12]:
city_pop = pd.DataFrame(
    [
        [808976, "San Francisco", "California"],
        [8363710, "New York", "New-York"],
        [413201, "Miami", "Florida"],
        [2242193, "Houston", "Texas"]
    ], index=[3,4,5,6], columns=["population", "city", "state"])
city_pop

   population           city       state
3      808976  San Francisco  California
4     8363710       New York    New-York
5      413201          Miami     Florida
6     2242193        Houston       Texas

In [13]:
pd.merge(left = city_loc, right = city_pop, on= "city")

  state_x           city        lat         lng  population     state_y
0      CA  San Francisco  37.781334 -122.416728      808976  California
1      NY       New York  40.705649  -74.008344     8363710    New-York
2      FL          Miami  25.791100  -80.320733      413201     Florida

In [14]:
pd.merge(left = city_loc, right = city_pop, on= "city", how = "outer")

  state_x            city        lat         lng  population     state_y
0      OH       Cleveland  41.473508  -81.739791         NaN         NaN
1     NaN         Houston        NaN         NaN   2242193.0       Texas
2      FL           Miami  25.791100  -80.320733    413201.0     Florida
3      NY        New York  40.705649  -74.008344   8363710.0    New-York
4      UT  Salt Lake City  40.755851 -111.896657         NaN         NaN
5      CA   San Francisco  37.781334 -122.416728    808976.0  California

In [16]:
pd.merge(left = city_loc, right = city_pop, on= "city", how = "left" )

  state_x            city        lat         lng  population     state_y
0      CA   San Francisco  37.781334 -122.416728    808976.0  California
1      NY        New York  40.705649  -74.008344   8363710.0    New-York
2      FL           Miami  25.791100  -80.320733    413201.0     Florida
3      OH       Cleveland  41.473508  -81.739791         NaN         NaN
4      UT  Salt Lake City  40.755851 -111.896657         NaN         NaN

In [20]:
result = pd.concat([city_loc, city_pop], ignore_index = True)
result

        state            city        lat         lng  population
0          CA   San Francisco  37.781334 -122.416728         NaN
1          NY        New York  40.705649  -74.008344         NaN
2          FL           Miami  25.791100  -80.320733         NaN
3          OH       Cleveland  41.473508  -81.739791         NaN
4          UT  Salt Lake City  40.755851 -111.896657         NaN
5  California   San Francisco        NaN         NaN    808976.0
6    New-York        New York        NaN         NaN   8363710.0
7     Florida           Miami        NaN         NaN    413201.0
8       Texas         Houston        NaN         NaN   2242193.0

In [23]:
#Load dataset

df = pd.read_csv(r"D:\Vipin HP Backup 10-11-25\Users\user\Desktop\New folder (5)\Desktop\titanic.csv")

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [26]:
df.shape

(891, 12)

In [27]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [30]:
#selecting a single column
df['Age'].head(10)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [31]:
#selecting multiple columns

df[["Age", "Sex", "Fare"]].head()

    Age     Sex     Fare
0  22.0    male   7.2500
1  38.0  female  71.2833
2  26.0  female   7.9250
3  35.0  female  53.1000
4  35.0    male   8.0500

In [32]:
df1 = df[["Age", "Sex", "Fare"]]
df1.head()

    Age     Sex     Fare
0  22.0    male   7.2500
1  38.0  female  71.2833
2  26.0  female   7.9250
3  35.0  female  53.1000
4  35.0    male   8.0500

In [33]:
#selecting rows

df.iloc[10]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

In [39]:
df[df["Survived"]==1].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [38]:
df[df["Sex"]== "female"].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [41]:
df[df["Survived"]==1].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [42]:
df[(df["Sex"]== 'female') & (df["Survived"] == 1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [43]:
#Data Slicing

df.loc[0:10, ['Name', 'Age', 'Sex']]

                                                 Name   Age     Sex
0                             Braund, Mr. Owen Harris  22.0    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                              Heikkinen, Miss. Laina  26.0  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                            Allen, Mr. William Henry  35.0    male
5                                    Moran, Mr. James   NaN    male
6                             McCarthy, Mr. Timothy J  54.0    male
7                      Palsson, Master. Gosta Leonard   2.0    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0  female
10                    Sandstrom, Miss. Marguerite Rut   4.0  female

In [45]:
df.iloc[0:10, 3:5]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                           Allen, Mr. William Henry    male
5                                   Moran, Mr. James    male
6                            McCarthy, Mr. Timothy J    male
7                     Palsson, Master. Gosta Leonard    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                Nasser, Mrs. Nicholas (Adele Achem)  female

In [48]:
#Dropping Columns

df.drop('Cabin', axis = 1, inplace = True)

In [49]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [51]:
df.drop(['Name', 'Ticket'], axis = 1, inplace = True)
df.head()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [52]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [54]:
#Sorting data

df.sort_values(by = 'Fare', ascending = False).head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
258,259,1,1,female,35.0,0,0,512.3292,C
737,738,1,1,male,35.0,0,0,512.3292,C
679,680,1,1,male,36.0,0,1,512.3292,C
88,89,1,1,female,23.0,3,2,263.0000,S
27,28,0,1,male,19.0,3,2,263.0000,S

In [57]:
df.sort_values(['Pclass', 'Fare'], ascending = [True, False])

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
258,259,1,1,female,35.0,0,0,512.3292,C
679,680,1,1,male,36.0,0,1,512.3292,C
737,738,1,1,male,35.0,0,0,512.3292,C
27,28,0,1,male,19.0,3,2,263.0000,S
88,89,1,1,female,23.0,3,2,263.0000,S
...,...,...,...,...,...,...,...,...,...
378,379,0,3,male,20.0,0,0,4.0125,C
179,180,0,3,male,36.0,0,0,0.0000,S
271,272,1,3,male,25.0,0,0,0.0000,S
302,303,0,3,male,19.0,0,0,0.0000,S
597,598,0,3,male,49.0,0,0,0.0000,S

In [58]:
#Creating new variables

df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_Size
0,1,0,3,male,22.0,1,0,7.2500,S,2
1,2,1,1,female,38.0,1,0,71.2833,C,2
2,3,1,3,female,26.0,0,0,7.9250,S,1
3,4,1,1,female,35.0,1,0,53.1000,S,2
4,5,0,3,male,35.0,0,0,8.0500,S,1

In [59]:
df['Age_group'] = pd.cut(df['Age'], 
                         bins = [0, 12, 18, 35, 60, 100],
                         labels = ['Child', 'Teen', 'Young', 'Adult', 'Senior'])

In [60]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_Size,Age_group
0,1,0,3,male,22.0,1,0,7.2500,S,2,Young
1,2,1,1,female,38.0,1,0,71.2833,C,2,Adult
2,3,1,3,female,26.0,0,0,7.9250,S,1,Young
3,4,1,1,female,35.0,1,0,53.1000,S,2,Young
4,5,0,3,male,35.0,0,0,8.0500,S,1,Young

In [61]:
df[['Age', 'Age_group']].head(10)

    Age Age_group
0  22.0     Young
1  38.0     Adult
2  26.0     Young
3  35.0     Young
4  35.0     Young
5   NaN       NaN
6  54.0     Adult
7   2.0     Child
8  27.0     Young
9  14.0      Teen

In [62]:
#Frequency Count

df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [63]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [65]:
df.Survived.value_counts(normalize = True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [66]:
pd.crosstab(df['Sex'], df['Survived'])

Survived    0    1
Sex
female     81  233
male      468  109

In [67]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [68]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64